/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type SearchSearchGetParams = {
order?: 'asc' | 'desc' | null;
query: string;
publications?: boolean | null;
abstract?: boolean;
multiple_genes?: boolean | null;
single_genes?: boolean | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
size?: number;
};
