/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  SearchSearchGetParams
} from './schemas';




  export const getFastAPI = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Search
 */
const searchSearchGet = (
    params: SearchSearchGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/search/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Snp Page
 */
const snpPageSnpSnpIdGet = (
    snpId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/snp/${snpId}`,options
    );
  }

/**
 * @summary Gene Page
 */
const genePageGeneGeneIdGet = (
    geneId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/gene/${geneId}`,options
    );
  }

/**
 * @summary Food Analize
 */
const foodAnalizeSnpsFoodAnalizeFoodNameGet = (
    foodName: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/snps/food-analize/${foodName}`,options
    );
  }

/**
 * @summary Health
 */
const healthHealthGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/health`,options
    );
  }

return {searchSearchGet,snpPageSnpSnpIdGet,genePageGeneGeneIdGet,foodAnalizeSnpsFoodAnalizeFoodNameGet,healthHealthGet}};
export type SearchSearchGetResult = AxiosResponse<unknown>
export type SnpPageSnpSnpIdGetResult = AxiosResponse<unknown>
export type GenePageGeneGeneIdGetResult = AxiosResponse<unknown>
export type FoodAnalizeSnpsFoodAnalizeFoodNameGetResult = AxiosResponse<unknown>
export type HealthHealthGetResult = AxiosResponse<unknown>
